module.exports = {
    'packaged-groats': 'Фасовані крупи',
    'pasta': 'Макаронні вироби',
    'weight-products': 'Ваговий товар',
    'oil': 'Олія',
    'canned-food': 'Консерви',
    'dairy-products': 'Молочні продукти',
    'sauces': 'Майонез, кетчуп, соуси',
    'spices': 'Приправи і спеції',
    'drinks': 'Чай, кава, напої',
    'water-and-juices': 'Вода і соки',
    'sweets-and-cookies': 'Солодощі, печиво',
    'children-products': 'Дитячі товари',
    'hygiene-products': 'Засоби гігієни',
    'paper-and-napkins': 'Папір, серветки',
    'sponges-and-cloths': 'Губки, ганчірки',
    'kitchen-and-bath': 'Кухня, ванна',
    'household-chemicals': 'Побутова хімія',
    'household-goods': 'Господарські товари',
    'animal-feed': 'Корми, комбікорми',
    'fertilizers': 'Мінеральні добрива',
    'stationery': 'Канцтовари',
    'batteries': 'Батарейки',
    'bags-glue-lighters': 'Пакет, клей, запальнички',
    'other-products': 'Інші товари',
}
  